language: python
python:
  - "2.7"
  - "3.6"
  - "3.7-dev"
# command to install dependencies
install:
  - pip install .
# command to run tests
script:
  - echo "skipping tests"

deploy:
  provider: pypi
  user: SamSchott
  skip_existing: true
  password:
    secure: dNW/oquNYqsz0g/c6Qsrp3gi1hBrlzQrrE6jMTywUFvk0OADTbkfnSyDnzYlpPTJfUjeoPEx6pADLtNctg3zECuK2DnRVA3CLSlUwY0doIQJ/IGtdTmafVmuR9soiN/4jr55Ks7c9Skr8aSoOjzjA77QIGm00JoiA53MLAAgA3O8tpHIlARoPKw5APzC06LyxdKV6i4UdoHDzDqT2jYvOhV3aXEdaDnv1T7EO0I7qr9RE3ZQjcRsWXg0u1zrF+I/PgyVpS4ypPFkXUvzmtgu17u6mtAqQvpb7pKqxzZdrv7PaA6wZdaiV/LoWCjAiytPZBPeu5788stvQdHhkOon0x1/vAgnSJ6lGWLxZwgDUHuxBSCfCNwsQtEvCR8lxf6ollBM84MLqjSyCUXgnhSs8cCPlgwCv9Qm6F8Zg+0cAhVfII4DupTBkT0jXmLqt0DOJnKzprRhpV/ql3tPWlQMH60/b/zCxIqvQfFE/02UE38UQ1dHloEANf0qBTMt9nqbP2ZdStoQO4IvsXkCaBqcRU6Kqk+kORb4hSEQlwqIlCSychVnxrU9DwJEpsYAsGkCYZfj5dY5t+pJm1xob0UaAxT3wJH9KBSRSusjSV2vfQsL0U4xwTrirSlpDJnopNsQd+2LXwX8bLnAq59FKU3qH4bFTzZvblgmqzRab2rM224=
