language: python
python:
- '2.7'
- '3.6'
- 3.7-dev
install:
- pip install .
script:
- echo "skipping tests"
deploy:
  provider: pypi
  user: SamSchott
  skip_existing: true
  on:
    tags: true
  password:
    secure: U4jeILNzQq/JMISz4KRQUpgzy/8zIa9NcdVnJrtS314fO+XMf7UJvWIi/2xqYIYevJcWLRpqRTAotL11ooYEjUKhblIW9Y2cXyBSbrsJ7ZoO/WH7Alzb3ESMXUazbasAbz6gMPDyncd6WjimXJ0TGHkdnVCsAKbH+Rg0GauFXmX9J/otTKu68HHwMBNa5i88n9fTrdYvyATgXuDmYkxYcSWZjSiVDGPQM33UeFV6tUGS14c7hdGjTPIp8IK+jK3hLODgS+q1865xU+rIE92cwK9v3W/sdI4wmP07Wvq2Cd0K+1yUJQcUiniqValdX9UumK4eLGEOBn59TCx9284TIotroPEyZlpcCh40XAnMGTSEkVy6cg6ewz8c3Okg8E9tR8uA8NwhPs7HyMybfJ9W0VL5pTcekynpWOi3SYInHBVVn4mfSHLO+smjm+/yzHDbe4TFEIKOsJUs294gJ8poUZIRq4A8n23IJ3y9dpMEDDzs/4YyDD0mkAFLGAbm1VZyl7se+ZEplrllSFfEcRYmY90YZdx2TwTCGpQTWQBVsVx1vGondGUGVl8jdXJGAe4AdKthQxwhLtpiPiy5kcFxgQzGVzeXqSTEdxNAuuK3s0UHPpzottI89ZsR9uPPtK0O8vciKm80fR+39SdrSms6k9zldsg9F6FUu2C1365brlM=
